### PR TITLE
Updating docker file for live reloading in docker

### PR DESCRIPTION
**Pull request by MichaelAndish**
Hey man, thanks for sharing 

In this way it works :)

### CODE REVIEW

**Comment by Its-Alex** [comment]
Hey @Mekaeil,

I tried to reuse this image recently and I have seen that it doesn't works very well. Normally this image is used to run without golang inside it. If I make two separate image:

- `itsalex/alpine-reflex`
- `itsalex/alpine-reflex-with-golang`

is it okay for you?

**Comment by MichaelAndish** [comment]
Hi @Its-Alex 

Recently I used this structure in my project but it didn't work and as you said in the second image which is without Golang, the path directory to put reflex didn't exist! so it's a reason I've had to add Golang to the second image as well. 

And also the reason for removing ARGs from the second image was for the path of the reflex, if you want to have the reflex the path of the reflex to copy is different, in the way that you wrote it doesn't work for me.

I've used it here: https://github.com/Mekaeil/Golang-QuizApp/blob/master/deployment/Dockerfile
and then when I wanted to run it I use the Makefile like below:
```
docker exec -it $(APP_DOCKER_NAME) reflex -r '(\.go)' -s -- sh -c 'go run bootstrap/main.go'
``` 

could be a good idea to have a separate image "with-golang" :)

**Comment by Its-Alex** [comment]
@Mekaeil I added new images, tell me if it's good for you 🙏

**Comment by Its-Alex** [comment]
@Mekaeil I will close this PR since there is no activity. Thanks for your contributions!

**Pull request closed without merging**
